# IMPORTANT: This file was generated by Cucumber 0.4.4
# Edit at your own peril - it's recommended to regenerate this file
# in the future when you upgrade to a newer version of Cucumber.
# Consider adding your own code to a new file instead of editing this one.
require 'logger'
require 'cucumber'
# Comment out the next line if you don't want Cucumber Unicode support
require 'cucumber/formatter/unicode'
# require 'cucumber/webrat/element_locator' # Lets you do table.diff!(element_at('#my_table_or_dl_or_ul_or_ol').to_table)
# require 'cucumber/rails/rspec'
require 'test/unit/assertions'
include Test::Unit::Assertions


if ENV['SAFARIWATIR']
  require 'safariwatir'
  Browser = Watir::Safari
  browser = Browser.new
elsif ENV['FIREWATIR']
  require 'firewatir'
  #include FireWatir::Dialog
  Browser = FireWatir::Firefox
  browser = Browser.new
elsif ENV['CHROMEWATIR']
  require 'chrome_watir'
  Browser = ChromeWatir::Browser
  browser = Browser.new
else
  case RUBY_PLATFORM
  when /darwin/
    require 'firewatir'
    Browser = FireWatir::Firefox
    browser = Browser.new
  when /win32|mingw/
    require 'watir'
    Browser = Watir::IE
    browser = Browser.new
    browser.speed = :fast
  when /java/
    require 'celerity'
    Browser = Celerity::Browser
    browser = Browser.new
  else
    raise "This platform is not supported (#{PLATFORM})"
  end
end

Before do
  @browser = browser
  @random = rand(9999999).to_s
  @environment = "http://www.google.com"
end

